databases: []
services:
  - type: web
    name: education-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: "20.18.0" # Убедитесь, что версия совпадает с вашей локальной
      - key: NPM_CONFIG_CACHE
        value: ~/.npm